### PR TITLE
Add metrics:delete/1

### PR DESCRIPTION
**Pull request by glejeune**
This is needed for https://github.com/benoitc/hackney/pull/351

And anyway, this is a cool missing feature

### CODE REVIEW

**Comment by glejeune** [comment]
@benoitc We need this to release a new version of [kafe](https://github.com/botsunit/kafe). Can you give me a feedback ? Thanks a lot.

**Comment by benoitc** [comment]
@glejeune Sorry for the delay, i'm quite busy these days. 

I will release later tonight. Thanks for the patch!

**Comment by glejeune** [comment]
@benoitc thanks !

**Comment by glejeune** [comment]
@benoitc do you plan to publish to hex.pm ? I'd be very grateful.

**Comment by benoitc** [comment]
i will today :)

**Comment by glejeune** [comment]
@benoitc please.... :mask:

**Comment by benoitc** [comment]
@glejeune will do today. Sorry have been sidetracked...

**Comment by benoitc** [comment]
hackney 2.2.0 has been uploaded to hex.pm

**Pull request merged**
