### PR TITLE
Add spiral metric type

### PR DESCRIPTION
**Pull request by puzza007**

### CODE REVIEW

**Comment by benoitc** [comment]
Thanks!

**Comment by puzza007** [comment]
My pleasure :) If you get a chance to publish to hex.pm at some stage I'd be very grateful.

**Comment by benoitc** [comment]
should be done today :)

**Comment by benoitc** [comment]
@puzza007 done metrics 1.1.0 released :)

**Comment by puzza007** [comment]
Thanks!

**Pull request merged**
